version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./postgresql.conf:/etc/postgresql.conf
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS=--auth-host=md5
    command: postgres -c config_file=/etc/postgresql.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=mypassword
      - DB_NAME=postgres

      - POOL_MODE=transaction
      - PGBOUNCER_IDLE_TRANSACTION_TIMEOUT=60
      - PGBOUNCER_POOL_MODE=transaction
      - PGBOUNCER_SERVER_RESET_QUERY_ALWAYS=0
      - PGBOUNCER_SERVER_LIFETIME=3600
      - PGBOUNCER_SERVER_IDLE_TIMEOUT=60
      - PGBOUNCER_MAX_DB_CONNECTIONS=200
      - PGBOUNCER_MAX_CLIENT_CONN=10000
      - PGBOUNCER_RESERVE_POOL_SIZE=50
      - PGBOUNCER_MIN_POOL_SIZE=2
      - PGBOUNCER_DEFAULT_POOL_SIZE=16
      - PGBOUNCER_IGNORE_STARTUP_PARAMETERS=extra_float_digits
      - PGBOUNCER_AUTH_TYPE=md5
      - PGBOUNCER_IDLE_TRANSACTION_TIMEOUT=60
    ports:
      - "15432:5432"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  kafka:
    image: apache/kafka:4.0.0
    restart: always
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:29092,CONTROLLER://:9093,EXTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - CLUSTER_ID=universe-labs-cluster
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: always
    container_name: kafka-ui
    ports:
      - "8180:8080"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  webapi:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    container_name: webapi
    environment:
      ASPNETCORE_ENVIRONMENT: Environment
      DbSettings__ConnectionString: Host=pgbouncer;Port=5432;Database=postgres;User Id=user;Password=mypassword;Pooling=false;
      DbSettings__MigrationConnectionString: Host=pgbouncer;Port=5432;Database=postgres;User Id=user;Password=mypassword;Pooling=false;
      KafkaSettings__BootstrapServers: kafka:29092
      KafkaSettings__ClientId: universe-labs-oms
      KafkaSettings__OmsOrderCreatedTopic: oms_order_created
      KafkaSettings__OmsOrderStatusChangedTopic: oms_order_status_changed
      ASPNETCORE_URLS: http://+:8080
    depends_on:
      pgbouncer:
        condition: service_started
      kafka:
        condition: service_healthy
    ports:
      - "5000:8080"
      - "5001:8081"
    networks:
      - app-network
    restart: unless-stopped
  
  consumer:
    build:
      context: .
      dockerfile: Consumer/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development 
      KafkaSettings__BootstrapServers: kafka:29092
      KafkaSettings__GroupId: universe-labs-oms-consumer
      KafkaSettings__OmsOrderCreatedTopic: oms_order_created
      KafkaSettings__OmsOrderStatusChangedTopic: oms_order_status_changed
      KafkaSettings__CollectBatchSize: 100
      KafkaSettings__CollectTimeoutMs: 500
      KafkaSettings__AutoOffsetReset: Latest
      KafkaSettings__EnableAutoCommit: "false" 
      KafkaSettings__SessionTimeoutMs: "60000"
      KafkaSettings__HeartbeatIntervalMs: "3000"
      KafkaSettings__MaxPollIntervalMs: "300000"

      HttpClient__Oms__BaseAddress: http://webapi:8080/

    depends_on:
      kafka:
        condition: service_healthy  
      webapi:
        condition: service_started

    deploy:
      replicas: 3

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  kafka_data: